'Hunt the Wumpus':
  image: fedora:28
  before_script:
    - cd Projects/wumpus/src
  script:
    - python3 -m pip install --upgrade pip setuptools wheel
    - python3 -m pip install -e .
    - python3 -m hakuna_matata.cli -agent asp -benchmark '../suite/world-*.txt'
